### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by AdrienLemaire** [cartant/eslint-plugin-react-etc#1]
> This packages contains a bunch of ESLint rules - some of which will require the use of TypeScript
> Some of the rules in this package require the ESLint TypeScript parser (indicated in the table below)

So far, I'm only seeing 1 rule that doesn't require typescript.

Are there existing undocumented rules, or rules being developed and that will come up soon?

I'm also interested in writing an eslint rule to request a Single Responsibility Principle docstring for each components (hopefully reducing the risk of complex components emerging). Would you be interested in contributions ?

**Comment by cartant** [comment]
> Are there existing undocumented rules, or rules being developed and that will come up soon?

Yes, but there is no road map. I have a bunch of ideas, but I have higher priority tasks. I just wanted to remove the 'beta' versioning. I didn't see the point in keeping it as a beta, just because there are rules and static validation approaches that I'd like the implement/explore.

Basically, the collection of RxJS lint rules that I've written started off in a package with only a one or two rules a grew into something much bigger. I anticipate that happening here, too.

> Would you be interested in contributions ?

Sure.

**Comment by AdrienLemaire** [comment]
Lovely, thanks!

**Comment by AdrienLemaire** [comment]
After some research, it seems that I can use existing rules like [require-file-overview from eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc#require-file-overview), so I do not need to write a custom eslint rule for it

**Comment by cartant** [comment]
No worries. Something to be aware of is that ESLint rules are composable - see [`eslint-rule-composer`](https://github.com/not-an-aardvark/eslint-rule-composer) and [this post of mine](https://ncjamieson.com/til-overriding-a-frozen-object/). So if what you want to do can be represented by feeding configuration into an existing rule - i.e. to reduce boilerplate from more general, verbose config - that's possible.
